### ISSUE TITLE
Inconsistent with the naming after change

### ISSUE THREAD

**Issue by oshezaf** [OTRF/OSSEM-CDM#4]
https://github.com/OTRF/OSSEM-CDM/blob/dacbc880b04e9b8ca0ae07b42614c1e0f9bcc8bf/schemas/entities/registry.yml#L48

The original registry fields are appended with "_modified" to reflect the value before change. However the fields "registry_value_name_modified" and "registry_value" do not keep this convention.

**Comment by Cyb3rPandaH** [comment]
Please review the changes in the following commit. Let us know if you have any questions. We can discuss it in our next community meeting.
