### ISSUE TITLE
snake_case to PascalCase

### ISSUE THREAD

**Issue by Cyb3rWard0g** [OTRF/OSSEM-CDM#6]
We want to be consistent with our recent collaboration efforts and it makes sense to migrate to PasacalCase.

**Comment by Cyb3rWard0g** [comment]
Decided to output both format for documentation

**Comment by Cyb3rWard0g** [comment]
from a programmatically perspective we are going to make sure those two formats are displayed in the official ossem website. We will use JupyterBook tabs. We are deciding to keep snak_case for our YAML files.

**Comment by Cyb3rWard0g** [comment]
https://jupyterbook.org/advanced/sphinx.html?highlight=tabs

**Comment by Cyb3rPandaH** [comment]
New Tasks:

- [ ] Update python script to create tabs to show different formats. One tab for snake_case, other for Pascal

**Comment by Cyb3rPandaH** [comment]
We have defined to use PascalCase.
See #30
