### ISSUE TITLE
File previous name is inconsistent with name

### ISSUE THREAD

**Issue by oshezaf** [OTRF/OSSEM-CDM#7]
https://github.com/OTRF/OSSEM-CDM/blob/dacbc880b04e9b8ca0ae07b42614c1e0f9bcc8bf/schemas/entities/file.yml#L103

previous_name includes path, while name does not. I suggest adding previous_path.

**Comment by Cyb3rPandaH** [comment]
Hey @oshezaf @Cyb3rWard0g Hope you guys are doing well. Here some ideas about this issue 😃 

I think we have two options:
1) Modifying **previous_name** to **previous_path**
The schema will consider this structure: file_name, file_path, file_previous_path
2) Modifying **previous_name** to **previous_path** AND Adding **previous_name**
The schema will consider this structure: file_name, file_previous_name, file_path, file_previous_path.

I would go with the second one. Even though it may involve more pre-processing of data to get the previous_name, it provides a complete schema.

**Comment by oshezaf** [comment]
Weekend here and already the summer break.... i will probably get to that Aug 29th or so.

**Comment by Cyb3rPandaH** [comment]
https://github.com/OTRF/OSSEM-CDM/commit/c55ba06b14198f66c8755f5a738e496e61a9b8af
